/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WitmerLab at Ohio University (https://sketchfab.com/witmerlab)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/visible-interactive-human-exploding-skull-252887e2e755427c90d9e3d0c6d3025f
Title: Visible Interactive Human - Exploding skull
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import skullGLB from '../models/visible_interactive_human_-_exploding_skull.glb'
// import { expo } from 'maath/dist/declarations/src/easing'

const SkullHeadScene = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(skullGLB)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="6718520e2371433bb7cfd89944ea6d9efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="_UNKNOWN_REF_NODE_fosterParent1">
                  <group
                    name="Skull"
                    position={[-0.249, 5.881, 0.961]}
                    rotation={[-2.352, 0.002, -0.08]}>
                    <group name="Cranium">
                      <group
                        name="Left_zygomaticSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.028, -0.013, -0.015]}>
                        <mesh
                          name="Left_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Left_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="OccipitalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.002, 0.023, 0.009]}>
                        <mesh
                          name="OccipitalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .OccipitalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Right_lacrimalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.006, -0.008, -0.007]}>
                        <mesh
                          name="Right_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Right_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Right_maxSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.02, -0.002, 0]}>
                        <mesh
                          name="Right_maxSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Right_maxSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="right_nasalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.008, -0.023, -0.022]}>
                        <mesh
                          name="right_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .right_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="right_palatineSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.016, 0.013, -0.014]}>
                        <mesh
                          name="right_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .right_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Right_ParietalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.022, -0.011, 0.009]}>
                        <mesh
                          name="Right_ParietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Right_ParietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Right_temporalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.023, -0.002, 0]}>
                        <mesh
                          name="Right_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Right_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Right_zygomaticSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[-0.022, -0.016, -0.014]}>
                        <mesh
                          name="Right_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Right_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group name="SphenoidSTL_Output_from_geomagic_Studio_________________________________________________">
                        <mesh
                          name="SphenoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .SphenoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="TeethSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0, -0.002, -0.015]}>
                        <mesh
                          name="TeethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .TeethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0
                              .geometry
                          }
                          material={materials.pasted__phong3}
                        />
                      </group>
                      <group
                        name="VomerSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.001, -0.01, -0.021]}>
                        <mesh
                          name="VomerSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .VomerSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="EthmoidSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.001, -0.008, -0.008]}>
                        <mesh
                          name="EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                        <mesh
                          name="EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="FrontalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.004, -0.044, -0.008]}>
                        <mesh
                          name="FrontalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .FrontalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Inferior_conchaeSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.002, -0.02, -0.02]}>
                        <mesh
                          name="Inferior_conchaeSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Inferior_conchaeSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="left_lacrimalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.008, -0.007, -0.007]}>
                        <mesh
                          name="left_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .left_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Left_maxillaSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.021, 0.002, 0]}>
                        <mesh
                          name="Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                        <mesh
                          name="Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Left_nasalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.008, -0.022, -0.022]}>
                        <mesh
                          name="Left_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Left_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Left_palatineSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.01, 0.015, -0.014]}>
                        <mesh
                          name="Left_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Left_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="Left_parietalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.023, -0.015, 0.017]}>
                        <mesh
                          name="Left_parietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Left_parietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                      <group
                        name="left_temporalSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0.039, 0.003, 0]}>
                        <mesh
                          name="left_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .left_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                    </group>
                    <group
                      name="Mandible1"
                      position={[-0.418, -1.66, 0.931]}
                      rotation={[-0.154, 0.022, 0.045]}>
                      <group
                        name="Lower_teethSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0, 0.01, -0.02]}>
                        <mesh
                          name="Lower_teethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .Lower_teethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0
                              .geometry
                          }
                          material={materials.pasted__phong3}
                        />
                      </group>
                      <group
                        name="MandibleSTL_Output_from_geomagic_Studio_________________________________________________"
                        position={[0, 0.027, -0.02]}>
                        <mesh
                          name="MandibleSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes
                              .MandibleSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                              .geometry
                          }
                          material={materials.pasted__lambert5}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(skullGLB)

export default SkullHeadScene
